import Head from "next/head";
import { ethers } from "ethers";

export default function Home() {
  const wave = () => {};

  return (
    <div>
      <Head>
        <title>👋 Wave At Me</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="mainContainer">
        <div className="hero">
          <h1 className="hero__title">👋 Hey there!</h1>

          <p className="hero__subtitle">
            I am Ore and I am a software developer? Connect your Ethereum wallet
            and wave at me!
          </p>

          <button className="btn primary-btn" onClick={wave}>
            👋 Wave at Me
          </button>
        </div>
      </main>
    </div>
  );
}
