import Head from 'next/head'
import { ethers } from "ethers";

export default function Home() {

  const wave = () => {
    
  }
 
  return (
    <div>
      <Head>
        <title>👋 Wave At Me</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="mainContainer">
       

      <div className="dataContainer">
        <div className="header">
        👋 Hey there!
        </div>

        <div className="bio">
        I am farza and I worked on self-driving cars so that's pretty cool right? Connect your Ethereum wallet and wave at me!
        </div>

        <button className="waveButton" onClick={wave}>
          Wave at Me
        </button>
      </div>
      </main>
    </div>
  )
}
